//includes generated by Qt Creator
#include "glavnookno.h"
#include "ui_glavnookno.h"
//includes for UI
#include "ui_izpis_zmagovalca.h"
#include "ui_izpis_neodloceno.h"
#include "ui_vnosimena1.h"
#include "ui_vnosimena2.h"
#include <QString>
#include <QInputDialog>
#include <QApplication>
//Includes for game logic
#include "cpp/igra.h"

//deklaracija objektov igra, igralec1 in igralec2
Igra* igra = NULL;
Igralec *i1 = NULL, *i2 = NULL;

glavnookno::glavnookno(QWidget *parent) :
  QMainWindow(parent),
  ui(new Ui::glavnookno)
{
  ui->setupUi(this);
  connect(ui->actionZacni_igro, SIGNAL(triggered()), this, SLOT(start()));


}

glavnookno::~glavnookno()
{
  //počisti memorijo ko zaključiš program
  if(igra != NULL){
    delete igra;
    igra = NULL;
  }
  if(i1 != NULL && i2 != NULL){
    delete i1;
    i1 = NULL;
    delete i2;
    i2 = NULL;
  }
  delete ui;
}

void glavnookno::start(){
  //Naslednji klici so uporabljeni za testiranje, ne spreminjati in obrisati pred finalnom različicom
  QMessageBox::about(this, "V razvoju", "To je test");
  //ovde se pokliče funkcija za začetek nove igre
  if(i1 == NULL && i2 == NULL)//ker igralci obstajajo tudi ko se igra zaključi, se funkcija za vnos imen kliče samo po prvem zagonu
    vnosImen();
  if(igra != NULL){
    delete igra;
    igra = NULL;
  }
  igra = new Igra(i1, i2);
  //izpis imen igralcev in posodabljanje števila zmag
  ui->txtIgralec1->setText(i1->getIme());
  ui->lblScore1->setText(QString::number(i1->getZmage()));
  ui->txtIgralec2->setText(i2->getIme());
  ui->lblScore2->setText(QString::number(i2->getZmage()));
  //Naslednji klici so uporabljeni za testiranje, ne spreminjati in obrisati pred finalnom različicom
  i1->zmaga();
}

//funkcija za vnos imen
void glavnookno::vnosImen(){
  QString imeI, imeII;
  QDialog *dI = new QDialog(0,0),
      *dII = new QDialog(0,0);
  Ui_vnosImena1 vi1;
  Ui_vnosImena2 vi2;
  vi1.setupUi(dI);
  dI->exec();
  imeI = vi1.txtIme->text();
  i1 = new Igralec(imeI, 1);
  vi2.setupUi(dII);
  dII->exec();
  imeII = vi2.txtIme->text();
  i2 = new Igralec(imeII, 2);
}

void glavnookno::zmagovalec(int z){
  QDialog* d = new QDialog(0,0);
  if(z==0){
    Ui_izpis_neodloceno nUi;
    nUi.setupUi(d);
    int s = d->exec();
    if (s == QDialog::Accepted){
      this->start();
    }
  } else {
    Ui_Izpis_zmagovalca zUi;
    zUi.setupUi(d);
    zUi.lblWin->setText(zUi.lblWin->text() + " " + QString::number(z));
    int s = d->exec();
    if (s == QDialog::Accepted){
      this->start();
    }
  }
}
