//includes generated by Qt Creator
#include "glavnookno.h"
#include "ui_glavnookno.h"
//includes for UI
#include "ui_izpis_zmagovalca.h"
#include "ui_izpis_neodloceno.h"
#include "ui_vnosimena1.h"
#include "ui_vnosimena2.h"
#include <QString>
#include <QInputDialog>
#include <QApplication>
#include <QWidget>
#include <QLabel>
#include <QTimer>

glavnookno::glavnookno(QWidget *parent) :
  QMainWindow(parent),
  ui(new Ui::glavnookno)
{
  // QTime mytimer;
  // mytimer.start();
  ui->setupUi(this);
  connect(ui->actionZacni_igro, SIGNAL(triggered()), this, SLOT(start()));
  this->igra = NULL;
  this->i1 = NULL;
  this->i2 = NULL;
  ch = new ClickHandler(this);
  igP = ui->igralnaP;
  for(int i = 0; i<6; i++)
    for(int j = 0; j<7; j++){
      QWidget* w = (QWidget*)ui->igralnaP->itemAtPosition(i, j+1)->widget();
      w->installEventFilter(ch);
    }
  statusLabel = new QLabel(this);
  statusLabel->setLayoutDirection(Qt::LeftToRight);
  ui->statusBar->addPermanentWidget(statusLabel);
}

glavnookno::~glavnookno()
{
  //počisti pomnilnik ko zaključiš program
  if(igra != NULL){
    delete igra;
    igra = NULL;
  }
  if(i1 != NULL && i2 != NULL){
    delete i1;
    i1 = NULL;
    delete i2;
    i2 = NULL;
  }
  delete ui;
}

void glavnookno::start(){
  //ovde se pokliče funkcija za začetek nove igre
  if(i1 == NULL && i2 == NULL)
    vnosImen();
  if(igra != NULL){
    delete igra;
    igra = NULL;
  }
  igra = new Igra(i1, i2);
  /*
  QTimer *timer=new QTimer(this);
  connect(timer,SIGNAL(timeout()),this,SLOT(izpiscas()));
  timer->start(1000);
  */
  this->updateUi();
  this->clearPolje();
}

/*
Q_SLOT void izpiscas(){
    //ui->cas->setText();
}
*/

//funkcija za vnos imen
void glavnookno::vnosImen(){
  QString imeI, imeII;
  QDialog *dI = new QDialog(0,0),
      *dII = new QDialog(0,0);
  Ui_vnosImena1 vi1;
  Ui_vnosImena2 vi2;
  vi1.setupUi(dI);
  dI->exec();
  imeI = vi1.txtIme->text();
  i1 = new Igralec(imeI, 1);
  vi2.setupUi(dII);
  dII->exec();
  imeII = vi2.txtIme->text();
  i2 = new Igralec(imeII, 2);
}

void glavnookno::setPolje(int x, int y, int i){
  QWidget *w = (QWidget*)ui->igralnaP->itemAtPosition(x, y+1)->widget();
  if(i == 1)
    w->setStyleSheet("border-image: url(:/img/tileR.png);");
  else if(i == 2)
    w->setStyleSheet("border-image: url(:/img/tileY.png);");
  this->updateUi();
}

void glavnookno::clearPolje(){
  for(int i = 0; i<6; i++)
    for(int j = 0; j<7; j++){
      QWidget* w = (QWidget*)ui->igralnaP->itemAtPosition(i, j+1)->widget();
      w->setStyleSheet("border-image: url(:/img/tile.png);\nbackground-color: rgba(255, 255, 255, 200);");
    }
}

void glavnookno::ilegalMove(){
  QMessageBox::warning(this, "Napaka", "Nedovoljen potez", QMessageBox::Ok, QMessageBox::Cancel);
}

void glavnookno::updateUi(){
  ui->txtIgralec1->setText(i1->getIme());
  ui->txtIgralec2->setText(i2->getIme());
  ui->lblScore1->setText(QString::number(i1->getZmage()));
  ui->lblScore2->setText(QString::number(i2->getZmage()));
  statusLabel->setText("Na vrsti je: " + igra->getNaVrsti()->getIme());
}



void glavnookno::zmagovalec(int z){
  QDialog* d = new QDialog(0,0);
  if(z==0){
    Ui_izpis_neodloceno nUi;
    nUi.setupUi(d);
    int s = d->exec();
    if (s == QDialog::Accepted){
      this->start();
    }
  } else {
    Ui_Izpis_zmagovalca zUi;
    zUi.setupUi(d);
    zUi.lblWin->setText(zUi.lblWin->text() + " " + QString::number(z));
    int s = d->exec();
    if (s == QDialog::Accepted){
        if(i1->getSt()==z){
            i1->zmaga();
        }else{
            i2->zmaga();
        }
        this->start();
    }
  }
}
